### ISSUE TITLE
What is the interface used in the docs?

### ISSUE THREAD

**Issue by santiagobasulto** [brexhq/prompt-engineering#3]
Sorry, this might be a dumb question. But what is the interface used tu simulate the assistant/user chat in the docs?

For the typography used, seems like an OpenAI playground, but I can't find it in my account.

Thanks!

![1](https://user-images.githubusercontent.com/89960/232420306-6fcdd6e2-b107-45d5-a1ee-4132fbb5853e.png)
![2](https://user-images.githubusercontent.com/89960/232420043-ebe5bcf1-25d9-4a31-ba84-13e9e1f62de2.png)

**Comment by stevekrenzel** [comment]
The playground found here: https://platform.openai.com/playground

Switch the `mode` to `chat`.

This is a good call out though. It'd be good to add instructions to the doc.

**Comment by santiagobasulto** [comment]
Maybe in the contributing guides?
